package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class DashboardController {
	@FXML
	private Button btnStudent;
	@FXML
	private Button btnOffice;
	@FXML
	private Button btnExam;
	@FXML
	private Button btnUniversity;

	// Event Listener on Button[#btnStudent].onAction
	@FXML
	public void StudentInformation(ActionEvent event) {
		
		try {
			Pane board = FXMLLoader.load(getClass().getResource("StudentAdmission.fxml"));
			Scene boardScene = new Scene(board);
			Stage boardStage= (Stage)((Node)event.getSource()).getScene().getWindow();
			boardStage.setScene(boardScene);
			boardStage.centerOnScreen();
			boardStage.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	// Event Listener on Button[#btnOffice].onAction
	@FXML
	public void OfficeInformation(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExam].onAction
	@FXML
	public void ExamInformation(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnUniversity].onAction
	@FXML
	public void UniversityInfo(ActionEvent event) {
		// TODO Autogenerated
	}
	public void backToDashboard(ActionEvent event) {
		
	}
}
