package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.io.IOException;

import ProssesingClass.LoginImplement;
import ProssesingClass.LoginInterface;
import collegePojo.UserLoginPojo;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginPageController {
	@FXML
	private TextField textUser;
	@FXML
	private PasswordField textPassword;
	@FXML
	private Button btnLogin;

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void loginProsses(ActionEvent event) {
		UserLoginPojo ulp = new UserLoginPojo();
		ulp.setUserName(textUser.getText());
		ulp.setPassword(textPassword.getText());
		
		LoginInterface li= new LoginImplement();
		boolean flag=li.LoginProsses(ulp);
		if(flag==true)
		{
			try 
			{
				AnchorPane board = FXMLLoader.load(getClass().getResource("Dashboard.fxml"));
				Scene boardScene = new Scene(board);
				Stage boardStage= (Stage)((Node)event.getSource()).getScene().getWindow();
				boardStage.setScene(boardScene);
				boardStage.centerOnScreen();
				boardStage.show();
			} 
			catch (Exception e) 
			{
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			System.out.println("Abhijit good Work");
		}
		else
		{
			System.out.println("Bad work");
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void exitProsses(ActionEvent event) {
		// TODO Autogenerated
	}
}
